---
name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths_ignore:
      - Dockerfile

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --diff

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          globs: '**/*.md'

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: yamllint --strict .

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pipx install cpplint
      - run: cpplint --recursive .

  cmakelang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pipx install cmakelang
      - run: find -name CMakeLists.txt -exec cmake-lint '{}' '+'
      - run: find -name CMakeLists.txt -exec cmake-format --check '{}' '+'
