---
name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths_ignore:
      - Dockerfile

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/ruff-action@v3

      - uses: astral-sh/ruff-action@v3
        with:
          args: format --diff

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          globs: '**/*.md'

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Lint YAML files
        run: yamllint --strict .

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install cpplint
        run: pipx install cpplint

      - name: Lint C/C++ files
        run: cpplint --recursive .

  cmakelang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install cmakelang
        run: pipx install cmakelang

      - name: Lint CMake files
        run: find -name CMakeLists.txt -exec cmake-lint '{}' '+'

      - name: Check formatting of CMake files
        run: find -name CMakeLists.txt -exec cmake-format --check '{}' '+'

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install clang-format
        run: pipx install clang-format

      - name: Check formatting of C/C++ files
        run: |
          find \( -name '*.[ch]' -o -name '*.[ch]pp' \) -print0 \
            | xargs -0 clang-format --Werror --dry-run --verbose
